# Generated by Django 5.1.2 on 2025-01-20 18:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_heading", models.CharField(blank=True, max_length=255)),
                ("subheading_1", models.CharField(blank=True, max_length=255)),
                (
                    "introduction_subheading_1",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introduction text for About this website section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutUsPageSubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subheading_2", models.CharField(max_length=255)),
                (
                    "introduction_subheading_2",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Introduction text for About us"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyright_statement_en",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Copyright statement in English"
                    ),
                ),
                (
                    "copyright_statement_cy",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Copyright statement in Welsh"
                    ),
                ),
            ],
        ),
    ]
