# Generated by Django 5.1.4 on 2025-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(help_text='Upload the OGL logo image', upload_to='footer_logos/')),
                ('copyright_statement_en', models.TextField(blank=True, help_text='Copyright statement in English')),
                ('copyright_statement_cy', models.TextField(blank=True, help_text='Copyright statement in Welsh')),
                ('open_government_licence_link', models.URLField(blank=True, help_text='Link to the Open Government Licence')),
                ('eur_lex_link', models.URLField(blank=True, help_text='Link to EUR-Lex terms')),
            ],
        ),
    ]
