# Generated by Django 5.1.4 on 2025-02-24 17:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0001_footer_and_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message_in_english', wagtail.fields.RichTextField(blank=True)),
                ('message_in_welsh', wagtail.fields.RichTextField(blank=True)),
            ],
        ),
    ]
