# Generated by Django 5.1.4 on 2025-01-16 09:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0001_initial'),
        ('wagtailcore', '0096_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for About Us')),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Main content for About Us')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
