# Generated by Django 5.0.7 on 2024-08-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0002_alter_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCompleteness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ukpga', 'ukpga')], max_length=5, unique=True)),
                ('cutoff', models.PositiveSmallIntegerField(help_text='first complete year', null=True)),
            ],
            options={
                'verbose_name_plural': 'dataset completeness',
            },
        ),
    ]
