# Generated by Django 5.1.4 on 2025-01-16 09:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0002_aboutuspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='copyright_statement_cy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Copyright statement in Welsh'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_statement_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Copyright statement in English'),
        ),
    ]
