# Generated by Django 5.1.4 on 2025-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0004_remove_footer_eur_lex_link_remove_footer_logo_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUsPage',
        ),
    ]
