# Generated by Django 5.1.4 on 2025-01-16 10:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0006_delete_aboutuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, max_length=255)),
                ('subheading_1', models.CharField(blank=True, max_length=255)),
                ('introduction_subheading_1', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for About this website section')),
                ('subheading_2', models.CharField(max_length=255)),
                ('introduction_subheading_2', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for About us')),
                ('bullet_list_subheading_2', wagtail.fields.RichTextField(blank=True, help_text='bulleted list for About us')),
            ],
        ),
    ]
