# Generated by Django 5.1.4 on 2025-01-16 10:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0007_aboutuspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='introduction_part2_subheading_2',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction text for About us'),
        ),
    ]
