# Generated by Django 5.1.4 on 2025-01-16 12:57

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0008_aboutuspage_introduction_part2_subheading_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPageSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading_2', models.CharField(max_length=255)),
                ('introduction_subheading_2', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for About us')),
            ],
        ),
    ]
