# Generated by Django 5.1.4 on 2025-01-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgu2', '0009_aboutuspagesubsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='bullet_list_subheading_2',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='introduction_part2_subheading_2',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='introduction_subheading_2',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='subheading_2',
        ),
    ]
