TYPES = {
    'ukpga': "UK Public General Acts",
    'ukla': "UK Local Acts",
    'apgb': "Acts of the Parliament of Great Britain",
    'aep': "Acts of the English Parliament",
    'aosp': "Acts of the Old Scottish Parliament",
    'asp': "Acts of the Scottish Parliament",
    'aip': "Acts of the Old Irish Parliament",
    'apni': "Acts of the Northern Ireland Parliament",
    'mnia': "Measures of the Northern Ireland Assembly",
    'nia': "Acts of the Northern Ireland Assembly",
    'ukcm': "Church Measures",
    'asc': "Acts of Senedd Cymru",
    'anaw': "Acts of the National Assembly for Wales",
    'mwa': "Measures of the National Assembly for Wales",
    'uksi': "UK Statutory Instruments",
    'ssi': "Scottish Statutory Instruments",
    'wsi': "Wales Statutory Instruments",
    'nisr': "Northern Ireland Statutory Rules",
    'nisi': "Northern Ireland Orders in Council",
    'nisro': "Northern Ireland Statutory Rules and Orders",
    'eur': "Regulations originating from the EU",
    'eudn': "Decisions originating from the EU",
    'eudr': "Directives originating from the EU",
}

AFFECTING_YEARS = range(2002, 2026)
